"""conversation persona and custom_instructions

Revision ID: 3492d138d0d6
Revises: ef12a5cd32fb
Create Date: 2026-07-06 03:33:55.229924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3492d138d0d6'
down_revision: Union[str, Sequence[str], None] = 'ef12a5cd32fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('persona', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('custom_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'custom_instructions')
    op.drop_column('conversations', 'persona')
    # ### end Alembic commands ###
