"""token usage and message seq

Revision ID: f4da256bb4a1
Revises: 34b9d346d5c7
Create Date: 2026-07-06 10:57:30.859562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4da256bb4a1'
down_revision: Union[str, Sequence[str], None] = '34b9d346d5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('seq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # Backfill turn order for existing transcripts from insert order — the
    # best approximation available for rows that predate the column.
    op.execute(
        """
        UPDATE messages SET seq = t.rn - 1
        FROM (
            SELECT id, row_number() OVER (
                PARTITION BY conversation_id ORDER BY id
            ) AS rn
            FROM messages
        ) t
        WHERE messages.id = t.id
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'seq')
    op.drop_column('conversations', 'token_usage')
    # ### end Alembic commands ###
